### ISSUE TITLE
Music!

### ISSUE THREAD

**Issue by idResponse** [endless-sky/endless-sky.github.io#10]
There's no music... It's kind of cool and what space really is like, but I would still enjoy a soundtrack.
I would enjoy writing that soundtrack.
Do you guys need a soundtrack?

[Matt Friedly - Zinlet Minstrels.zip](https://github.com/endless-sky/endless-sky.github.io/files/1471569/Matt.Friedly.-.Zinlet.Minstrels.zip)

**Comment by Fzzr** [comment]
Yep, definitely on the roadmap https://github.com/endless-sky/endless-sky/wiki/DevelopmentRoadmap#goals-for-version-100. I think the issue is more the code to play it at appropriate times than obtaining the actual music. There's no doubt tons of great CC-BY-SA music out there.

**Comment by SHADOWELITE7** [comment]
this is a website repo you probably would have more luck either putting it out in [Endless sky Repo](https://github.com/endless-sky/endless-sky) or make a pull request to add your music so you can make your contributions to the endless sky game
