### ISSUE TITLE
No direct link to GitHub repo main page

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky.github.io#18]
The website does not have an direct link to the GitHub repo main page. I would expect it to have a "Fork me on GitHub" banner or something similar so that users can easily go to it. So I'd like to request that such a banner, or something similar, be added.

Users can get to the repo by clicking on "Downloads", "Wiki", or "Bug Reports", but those aren't the obvious thing that people would go to if they just want to "get to the GitHub repo."

**Comment by quyykk** [comment]
Resolved in #28
