### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky.github.io#19]
In the last years, it has become the defacto standard to redirect requests to https. This is worth it even for sites without sensitive data being transmitted, since browsers are becoming increasingly cautious of non-encrypted connections.

Thus, one should consider redirecting traffic for this website as well.

https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by samrocketman** [comment]
In your GitHub pages settings it's as easy as checking a box.  It'll use Let's Encrypt CA certificates automatically managed by GitHub.

**Comment by jwfxpr** [comment]
+1 on this; weird to see any page at all without HTTPS, and weird that any software project wouldn't consider this important. Honestly, it immediately makes me think your code will be rubbish, and I won't be interested in installing or contributing to the project with something so fundamental ignored.

**Comment by MCOfficer** [comment]
> 
> 
> +1 on this; weird to see any page at all without HTTPS, and weird that any software project wouldn't consider this important. Honestly, it immediately makes me think your code will be rubbish, and I won't be interested in installing or contributing to the project with something so fundamental ignored.

It's not that it's not *considered* important, it's just that MZ hasn't been able to do *anything* aside from releases in the past year or so :/

**Comment by tehhowch** [comment]
This is complete now 🎊
