### ISSUE TITLE
debian package link broken

### ISSUE THREAD

**Issue by anarcat** [endless-sky/endless-sky.github.io#2]
http://endless-sky.github.io/ links to https://mentors.debian.net/package/endless-sky which is now missing:

```
[995]anarcat@angela:~$ curl -I https://mentors.debian.net/package/endless-sky
HTTP/1.1 302 Found
Date: Mon, 08 Feb 2016 01:45:37 GMT
Server: Apache/2.2.22 (Debian)
Pragma: no-cache
Cache-Control: no-cache
Location: https://mentors.debian.net/packages/index?packagename=None
```

i suspect this is because the package expired from mentors. it is now in debian sid, but that is not really available to everyone running debian. the ITP was just closed: http://bugs.debian.org/782846

until it hits debian stretch, it cannot be backported to stable publicly either: http://tracker.debian.org/endless-sky

**Comment by anarcat** [comment]
FWIW, the trusty PPA works on Debian Jessie:

```
deb http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu trusty main
```

**Comment by anarcat** [comment]
well, "works" as in "i can install it", but it actually segfaults. trying to build from source now.

**Comment by endless-sky** [comment]
Yes, I just got an automatic email today saying it had been removed from mentors because it's accepted into the official repository. Hopefully that means in a day or two the package will show up on packages.debian.org, but it's not visible there yet.

**Comment by MCOfficer** [comment]
bump - the new link (unless you want to be version-specific) is https://packages.debian.org/endless-sky
