### ISSUE TITLE
Styleguide needs to be linked from the main page.

### ISSUE THREAD

**Issue by shnwnd** [endless-sky/endless-sky.github.io#22]
The styleguide (C++ style guide, there may be a new one for /data/ ) need to be easily discoverable, I suggest adding a new link to the navigation menu/box. (terminology escapes me)

**Comment by tehhowch** [comment]
The style guide is linked from the game's Wiki homepage (which is linked from the website) and from the game's CONTRIBUTING file:

https://github.com/endless-sky/endless-sky/blob/master/CONTRIBUTING.md#posting-pull-requests

> * If changing the C++ code, follow the [coding standard](http://endless-sky.github.io/styleguide/styleguide.xml).

**Comment by samrocketman** [comment]
IMO the contributing doc makes the most sense.

**Comment by quyykk** [comment]
Yeah I don't really see the need to have a discoverable link on the homepage as well. If someone wants to contribute, they'll find it.
