### ISSUE TITLE
Update SDL2 version on Windows

### ISSUE THREAD

**Issue by thomasballinger** [endless-sky/endless-sky.github.io#26]
In order to use new functionality in SDL2 since the currently used version 2.0.3 it would be nice to update it. https://github.com/endless-sky/endless-sky/issues/6315 is the motivation for this at the moment, we might find other goodies in there useful too.

@MCOfficer points out previous updates of these dependencies: https://github.com/endless-sky/endless-sky.github.io/commits/master/win64-dev.zip

I don't know the implications of an upgrade like this would be besides that it's ~6 years of updates to go all the way to 2.0.10 so it would be important to test.

I saw [a comment](https://github.com/endless-sky/endless-sky/pull/5704#pullrequestreview-585089614) that "we won't be updating the precompiled library versions" from @tehhowch that sounded related but after reading the related Discord conversation I don't think it is.

**Comment by tehhowch** [comment]
One of the delays in getting 0.9.15 out is I am wanting to update our development libraries as well, so that the version is consistent across platforms. Updating the distributed SDL library is a part of that.

**Comment by Terin** [comment]
As mentioned in #6315, I think a later version of SDL would also let us override Windows blowing the window up to a blurry image with higher DPI settings. Since we have a native DPI/zoom setting in game, Endless Sky should definitely handle that.

**Comment by quyykk** [comment]
This was done in #27, now the current SDL version is 2.24.0 on Windows.
